# Generated by Django 3.2.6 on 2021-10-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='phone_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='핸드폰 번호'),
        ),
    ]
